#!/bin/sh
#PBS -N B9-Sc_o2
#PBS -l nodes=1:ppn=32:debug
#PBS -l walltime=2:00:00
#PBS -j oe
#PBS -V
#PBS -e error.log

curr_dir=${PBS_O_WORKDIR}
cd $curr_dir


NPROCS=`wc -l < $PBS_NODEFILE`
NNODES=`uniq $PBS_NODEFILE | wc -l`
HOSTS=`cat $PBS_NODEFILE | uniq | tr '\n' "," | sed 's|,$||'`
mpirun -np $NPROCS --host $HOSTS /home/phd/15/mrcrites/vasp5.3.5/vasp.5.3/vasp

