#!/bin/bash -l

### This file contains SGE Job submit script for running mpi (orte) task ###
### Set the shell environment ###

#$ -S /bin/bash

### Change to Current Working Directory ###

#$  -cwd

### Initialize the variables

#$ -V

## #Name of the Job (This should be changed to anything suitable) ###

#$ -N B10-doped_dos_o2

### Use the Intel MPI Parallel Environment with <n> cores. Please change the core value suiting your job ###
### Please do not change anything other than the no. of cores ###

#$ -pe orte 32


echo "======================================="
echo "Starting the job at: " `date`
echo "Starting the job on: " `hostname`
echo "Total cores demanded: " $NSLOTS
echo "Job Name given: " $JOB_NAME
echo "JobID: " $JOB_ID
echo "======================================="
echo "Participating compute nodes:"
echo "======================================="
cat $PE_HOSTFILE > HF.`echo $JOB_NAME`.`echo $JOB_ID`
cut -d'.' -f1 HF.`echo $JOB_NAME`.`echo $JOB_ID` >> MHF.`echo $JOB_NAME`.`echo $JOB_ID`
cat MHF.`echo $JOB_NAME`.`echo $JOB_ID`
echo "======================================="

echo "Starting MPI Job.."

for i in Sc Ti V Cr Mn Fe Co Ni Cu Zn
do
cd B9_B,$i
cd adsorb_o2_p
mkdir DOS
cd DOS
cp ../CHGCAR .
cp ../KPOINTS .
cp ../CONTCAR POSCAR
cp ../POTCAR .
cp ../../../INCAR-dos .
w=`grep "wigner-seitz" ../OUTCAR | awk '{printf "\%8.3f", $6}'`
echo "RWIGS = $w" >> INCAR
mpirun -np $NSLOTS /share/apps/code/vasp.5.4.1-sol/vasp.5.4.1/bin/vasp_std
cd ../../../
done

### Please change the executable only (last word) ###

#mpirun -np $NSLOTS --hostfile MHF.`echo $JOB_NAME`.`echo $JOB_ID` /share/apps/code/vasp.5.4.1-sol/vasp.5.4.1/bin/vasp_std 
#rm -f HF.`echo $JOB_NAME`.`echo $JOB_ID`
#rm -f MHF.`echo $JOB_NAME`.`echo $JOB_ID`
echo "MPI Execution over. Please wait for SGE to cleanup."

### End of script ###
exit 0
